name: Test Action

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Quality Check
      id: git-quality-check
      uses: gcattan/git-quality-check@v0.1.2
      with:
        badWords: WIP, todo
        mainBranches: main
    - name: Check outputs
      run: |
        test "${{ steps.git-quality-check.outputs.score }}" != ""